version: '3'

services:
  web:
    build: ./web
    restart: always
    ports:
      - "22446:8000"
  bot:
    build: ./bot
    command: phantomjs --ignore-ssl-errors=true --local-to-remote-url-access=true --web-security=false --ssl-protocol=any bot.js
    restart: always
    environment:
      - DOMAIN=3.0.58.217
      - PORT=2600 # Jangan lupa ganti
