version: '3'

services:
    extra_secure_cryptography:
        build: .
        restart: always
        ports:
          - 25624:1337
        security_opt:
          - seccomp:unconfined
          - apparmor:unconfined
