# Generated by Django 3.1.1 on 2020-09-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0002_auto_20200925_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_queue', models.CharField(max_length=100)),
            ],
        ),
    ]
